object FrShowImg: TFrShowImg
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'FrShowImg'
  ClientHeight = 480
  ClientWidth = 640
  Color = clBtnFace
  TransparentColor = True
  TransparentColorValue = clNone
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  Position = poMainFormCenter
  WindowState = wsMaximized
  OnKeyDown = FormKeyDown
  TextHeight = 15
  object PnlContent: TPanel
    AlignWithMargins = True
    Left = 3
    Top = 3
    Width = 634
    Height = 474
    Align = alClient
    Color = 5969410
    ParentBackground = False
    ShowCaption = False
    TabOrder = 0
    ExplicitLeft = 120
    ExplicitTop = 80
    ExplicitWidth = 185
    ExplicitHeight = 41
    object FocusedImg: TImage
      AlignWithMargins = True
      Left = 9
      Top = 9
      Width = 616
      Height = 456
      Margins.Left = 8
      Margins.Top = 8
      Margins.Right = 8
      Margins.Bottom = 8
      Align = alClient
      ExplicitLeft = 288
      ExplicitTop = 104
      ExplicitWidth = 105
      ExplicitHeight = 105
    end
  end
end
