unit uConst.sys;

interface

const
  DEFAULT_COLLOR = $FF3F3F3F;
  WIN_BAR_COLOR = $FF266D5E;
  SUCCESS_COLLOR = $FF5DC455;
  WARNING_COLOR  = $FFEADD2F;
  ERROR_COLOR  = $FFD14F40;
  QUEST_COLOR  = $FF407CD1;

implementation

end.
