object TFormCadPadrao: TTFormCadPadrao
  Left = 0
  Top = 0
  Caption = 'Cadastro'
  ClientHeight = 441
  ClientWidth = 624
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  OnClose = FormClose
  OnCreate = FormCreate
  OnShow = FormShow
  TextHeight = 15
  object Panel1: TPanel
    AlignWithMargins = True
    Left = 3
    Top = 3
    Width = 618
    Height = 41
    Align = alTop
    Color = 16449599
    ParentBackground = False
    TabOrder = 0
    object LbNome: TLabel
      AlignWithMargins = True
      Left = 11
      Top = 4
      Width = 80
      Height = 33
      Margins.Left = 10
      Align = alLeft
      Caption = 'LbNome'
      Color = 14254118
      Font.Charset = ANSI_CHARSET
      Font.Color = 15263976
      Font.Height = -21
      Font.Name = 'Roboto'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
      ExplicitHeight = 25
    end
  end
  object Panel2: TPanel
    AlignWithMargins = True
    Left = 3
    Top = 50
    Width = 618
    Height = 341
    Align = alClient
    Color = 16085138
    ParentBackground = False
    TabOrder = 1
    object Panel4: TPanel
      AlignWithMargins = True
      Left = 9
      Top = 4
      Width = 600
      Height = 331
      Margins.Left = 8
      Margins.Right = 8
      Margins.Bottom = 5
      Align = alClient
      Color = 13671851
      ParentBackground = False
      TabOrder = 0
      object Panel5: TPanel
        AlignWithMargins = True
        Left = 4
        Top = 4
        Width = 592
        Height = 152
        Align = alTop
        Color = 16638956
        ParentBackground = False
        TabOrder = 0
      end
      object Panel6: TPanel
        AlignWithMargins = True
        Left = 4
        Top = 162
        Width = 592
        Height = 165
        Align = alClient
        Caption = 'Panel5'
        TabOrder = 1
        object GrdRegistro: TDBGrid
          Left = 1
          Top = 1
          Width = 590
          Height = 163
          Align = alClient
          DataSource = DSRegistro
          TabOrder = 0
          TitleFont.Charset = DEFAULT_CHARSET
          TitleFont.Color = clWindowText
          TitleFont.Height = -12
          TitleFont.Name = 'Segoe UI'
          TitleFont.Style = []
        end
      end
    end
  end
  object Panel3: TPanel
    AlignWithMargins = True
    Left = 3
    Top = 397
    Width = 618
    Height = 41
    Align = alBottom
    Color = 14254118
    ParentBackground = False
    TabOrder = 2
    object Button1: TButton
      AlignWithMargins = True
      Left = 4
      Top = 6
      Width = 75
      Height = 29
      Margins.Top = 5
      Margins.Bottom = 5
      Align = alLeft
      Caption = 'Novo'
      TabOrder = 0
      OnClick = Button1Click
    end
    object Button2: TButton
      AlignWithMargins = True
      Left = 85
      Top = 6
      Width = 75
      Height = 29
      Margins.Top = 5
      Margins.Bottom = 5
      Align = alLeft
      Caption = 'Editar'
      TabOrder = 1
      OnClick = Button2Click
    end
    object Button3: TButton
      AlignWithMargins = True
      Left = 166
      Top = 6
      Width = 75
      Height = 29
      Margins.Top = 5
      Margins.Bottom = 5
      Align = alLeft
      Caption = 'Salvar'
      Enabled = False
      TabOrder = 2
      OnClick = Button3Click
    end
    object Button4: TButton
      AlignWithMargins = True
      Left = 247
      Top = 6
      Width = 75
      Height = 29
      Margins.Top = 5
      Margins.Bottom = 5
      Align = alLeft
      Caption = 'Cancelar'
      Enabled = False
      TabOrder = 3
      OnClick = Button4Click
    end
    object Button5: TButton
      AlignWithMargins = True
      Left = 576
      Top = 4
      Width = 38
      Height = 31
      Margins.Bottom = 5
      Align = alRight
      Caption = '>'
      TabOrder = 4
      OnClick = Button5Click
    end
    object BtPrior: TButton
      AlignWithMargins = True
      Left = 533
      Top = 4
      Width = 37
      Height = 31
      Margins.Bottom = 5
      Align = alRight
      Caption = '<'
      TabOrder = 5
      OnClick = BtPriorClick
    end
  end
  object MemRegistro: TFDMemTable
    FetchOptions.AssignedValues = [evMode]
    FetchOptions.Mode = fmAll
    ResourceOptions.AssignedValues = [rvSilentMode]
    ResourceOptions.SilentMode = True
    UpdateOptions.AssignedValues = [uvCheckRequired, uvAutoCommitUpdates]
    UpdateOptions.CheckRequired = False
    UpdateOptions.AutoCommitUpdates = True
    Left = 280
    Top = 146
  end
  object DSRegistro: TDataSource
    DataSet = MemRegistro
    Left = 376
    Top = 154
  end
end
